# Домашнее задание к занятию Troubleshooting

### Цель задания

Устранить неисправности при деплое приложения.

### Чеклист готовности к домашнему заданию

1. Кластер K8s.

### Задание. При деплое приложение web-consumer не может подключиться к auth-db. Необходимо это исправить

1. Установить приложение по команде:
```shell
kubectl apply -f https://raw.githubusercontent.com/netology-code/kuber-homeworks/main/3.5/files/task.yaml
```
2. Выявить проблему и описать.
3. Исправить проблему, описать, что сделано.
4. Продемонстрировать, что проблема решена.

<-- Ответ

1. Ставим приложение


```commandline
kubectl apply -f https://raw.githubusercontent.com/netology-code/kuber-homeworks/main/3.5/files/task.yaml
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/netology-code/kuber-homeworks/main/3.5/files/task.yaml": namespaces "web" not found
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/netology-code/kuber-homeworks/main/3.5/files/task.yaml": namespaces "data" not found
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/netology-code/kuber-homeworks/main/3.5/files/task.yaml": namespaces "data" not found

kubectl create ns web
namespace/web created

kubectl create ns data
namespace/data created

kubectl apply -f        
deployment.apps/web-consumer created
deployment.apps/auth-db created
service/auth-db created


kubectl get all -n data
NAME                           READY   STATUS    RESTARTS   AGE
pod/auth-db-7b5cdbdc77-j7lzq   1/1     Running   0          30s

NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/auth-db   ClusterIP   10.101.88.174   <none>        80/TCP    30s

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/auth-db   1/1     1            1           30s

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/auth-db-7b5cdbdc77   1         1         1       30s

kubectl get all -n web 
NAME                                READY   STATUS    RESTARTS   AGE
pod/web-consumer-5f87765478-dsdph   1/1     Running   0          42s
pod/web-consumer-5f87765478-smdj9   1/1     Running   0          42s

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/web-consumer   2/2     2            2           42s

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/web-consumer-5f87765478   2         2         2       42s
```

2. Выявляем проблему

```commandline
kubectl logs -n web web-consumer-5f87765478-dsdph 
curl: (6) Couldn't resolve host 'auth-db'
curl: (6) Couldn't resolve host 'auth-db'
curl: (6) Couldn't resolve host 'auth-db'
curl: (6) Couldn't resolve host 'auth-db'
curl: (6) Couldn't resolve host 'auth-db'
curl: (6) Couldn't resolve host 'auth-db'
```
Проблема в том что под web-consumer не ресолвит auth-db, так как они в разных нейм спейсах

3. Исправляем

```commandline
kubectl get deploy -n web web-consumer -o yaml > tmp.yaml && sed -i "s/namespace: web/namespace: auth-db/g" tmp.yaml && kubectl replace -f tmp.yaml
```

4. Проверяем

------